// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountBook(ctx context.Context) (int64, error)
	CountBookByIds(ctx context.Context, ids []uuid.UUID) (int64, error)
	CountBookInfo(ctx context.Context) (int64, error)
	CountBorrower(ctx context.Context) (int64, error)
	CountBorrowerByIds(ctx context.Context, ids []uuid.UUID) (int64, error)
	CountCategory(ctx context.Context) (int64, error)
	CountUser(ctx context.Context) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (*Book, error)
	CreateBookBorrower(ctx context.Context, arg CreateBookBorrowerParams) (*BookBorrower, error)
	CreateBookInfo(ctx context.Context, arg CreateBookInfoParams) (*BookInfo, error)
	CreateBorrower(ctx context.Context, arg CreateBorrowerParams) (*Borrower, error)
	CreateCategory(ctx context.Context, name string) (*Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteOneBookById(ctx context.Context, id uuid.UUID) (*Book, error)
	DeleteOneBookInfoById(ctx context.Context, id uuid.UUID) (*BookInfo, error)
	DeleteOneBorrowerById(ctx context.Context, id uuid.UUID) (*Borrower, error)
	DeleteOneCategoryById(ctx context.Context, id uuid.UUID) (*Category, error)
	DeleteOneUserById(ctx context.Context, id uuid.UUID) (*User, error)
	GetAllBookBorrowerByBookId(ctx context.Context, bookID uuid.UUID) ([]*BookBorrower, error)
	GetAllBookBorrowerByBorrowerId(ctx context.Context, borrowerID uuid.UUID) ([]*BookBorrower, error)
	GetOneBookBorrower(ctx context.Context, arg GetOneBookBorrowerParams) (*BookBorrower, error)
	GetOneBookById(ctx context.Context, id uuid.UUID) (*Book, error)
	GetOneBookInfoById(ctx context.Context, id uuid.UUID) (*BookInfo, error)
	GetOneBorrowerById(ctx context.Context, id uuid.UUID) (*Borrower, error)
	GetOneBorrowerByPhone(ctx context.Context, phone string) (*Borrower, error)
	GetOneCategoryById(ctx context.Context, id uuid.UUID) (*Category, error)
	GetOneUserById(ctx context.Context, id uuid.UUID) (*User, error)
	ListBook(ctx context.Context, arg ListBookParams) ([]*Book, error)
	ListBookByIds(ctx context.Context, arg ListBookByIdsParams) ([]*Book, error)
	ListBookInfo(ctx context.Context, arg ListBookInfoParams) ([]*BookInfo, error)
	ListBorrower(ctx context.Context, arg ListBorrowerParams) ([]*Borrower, error)
	ListBorrowerByIds(ctx context.Context, arg ListBorrowerByIdsParams) ([]*Borrower, error)
	ListCategory(ctx context.Context, arg ListCategoryParams) ([]*Category, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]*User, error)
	UpdateOneBookById(ctx context.Context, arg UpdateOneBookByIdParams) (*Book, error)
	UpdateOneBookInfoById(ctx context.Context, arg UpdateOneBookInfoByIdParams) (*BookInfo, error)
	UpdateOneBorrowerById(ctx context.Context, arg UpdateOneBorrowerByIdParams) (*Borrower, error)
	UpdateOneCategoryById(ctx context.Context, arg UpdateOneCategoryByIdParams) (*Category, error)
	UpdateOneUserById(ctx context.Context, arg UpdateOneUserByIdParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
