// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountCategory(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, name string) (*Category, error)
	DeleteOneCategoryById(ctx context.Context, id uuid.UUID) (*Category, error)
	GetOneCategoryById(ctx context.Context, id uuid.UUID) (*Category, error)
	ListCategory(ctx context.Context, arg ListCategoryParams) ([]*Category, error)
	UpdateOneCategoryById(ctx context.Context, arg UpdateOneCategoryByIdParams) (*Category, error)
}

var _ Querier = (*Queries)(nil)
