// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package db

import (
	"context"
)

const getAllUser = `-- name: GetAllUser :many
SELECT id, username, password, role, created_at, updated_at, deleted_at FROM "users"
LIMIT $1
OFFSET $2
`

type GetAllUserParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUser(ctx context.Context, arg GetAllUserParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
